export const Trans = [
  {
    bankName: "Kuda",
    typeofTrans: "Bank Transfer",
    amount: "5,000",
    name: "Holat",
    debitOrCredit: "debit",
    time: "07:43",
  },
  {
    bankName: "Airtel",
    typeofTrans: "Data",
    amount: "25",
    name: "Airtel 0704459392",
    debitOrCredit: "debit",
    time: "06:34",
  },
  {
    bankName: "GTB",
    typeofTrans: "Bank Transfer",
    amount: "250",
    name: "Olorunshola Tomi",
    debitOrCredit: "credit",
    time: "06:34",
  },
  {
    bankName: "Kuda",
    typeofTrans: "Bank Transfer",
    amount: "5,000",
    name: "Holat",
    debitOrCredit: "debit",
    time: "07:43",
  },
  {
    bankName: "Airtel",
    typeofTrans: "Data",
    amount: "25",
    name: "Airtel 0704459392",
    debitOrCredit: "debit",
    time: "06:34",
  },
  {
    bankName: "GTB",
    typeofTrans: "Bank Transfer",
    amount: "250",
    name: "Olorunshola Tomi",
    debitOrCredit: "credit",
    time: "06:34",
  },
];
